version: "3.8"

networks:
    nginx_network:
        external: true
    internal:

services:
    dashboard-api-app:
        container_name: dashboard-api-app
        working_dir: /app
        image: adhocore/phpfpm:8.1
        restart: always
#        environment:
#          PHP_MEMORY_LIMIT: 1024M
        networks:
            - internal
            - nginx_network
        volumes:
            - '.:/app'
            - './docker/php/overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        depends_on:
            - dashboard-api-database
    dashboard-api-database:
        image: postgres:11.1-alpine
        restart: always
        container_name: dashboard-api-database
        working_dir: /app
        networks:
            - internal
            - nginx_network
        environment:
            - POSTGRES_USER=oauth_user
            - POSTGRES_PASSWORD=UYaRCA7emd2szH47
            - POSTGRES_DB=users
        volumes:
            - .:/app
            - ./dashboard-api-database:/var/lib/postgresql/data
        ports:
            - '8033:5432'
    dashboard-api-nginx:
        image: nginx:alpine
        container_name: dashboard-api-nginx
        working_dir: /app
        restart: always
        networks:
            - internal
            - nginx_network
        ports:
            - "9030:80"
        volumes:
            - .:/app
            - ./docker/nginx/oauth.conf:/etc/nginx/conf.d/default.conf
    dashboard-api-composer:
        image: composer:latest
        container_name: dashboard-api-composer
        working_dir: /app
        command: update --ignore-platform-reqs
        volumes:
            - .:/app
        restart: on-failure
        depends_on:
            - dashboard-api-app
volumes:
  dashboard-api-database:
        driver: local
